### ISSUE TITLE
Give a detail readme for server

### ISSUE THREAD

**Issue by starsareintherose** [BioArchLinux/bioarchlinux-tools#1]
please give details for the server, or give a shell for each script.

For example, how to archive

r-spp
r-propr
r-catnet
r-pkgmaker

**Comment by sukanka** [comment]
## TLDR
For usage, run with argument -h.
## Detailed steps
0. copy all my py files to `Packages` dir.

1. update database
download the database from release, and move it to `/tmp/dbmanager/biometadata.db`, run this command to update database.
```
./dbmanager.py  -m "3.15" --db /tmp/dbmanager/biometadata.db
```
2. prepare the pkg list to be archived, say, a file named `pkglist.txt`, 
```
r-spp
r-propr
r-catnet
r-pkgmaker
```
3. run depends_updater `-a` means `auto archive`
```
./depends_updater.py -a -f pkglist.txt -db /tmp/dbmanager/biometadata.db -o out.txt
```
4. Check `out.txt`, you may need to add these pkgs to BioArch Repo

**Comment by starsareintherose** [comment]
what about archive? It's not safe to under Packages directory, better to run under Tools directory

**Comment by sukanka** [comment]
> what about archive? It's not safe to under Packages directory, better to run under Tools directory

`archive` is merged into `depends_updater`. Run it in Package dir, and check the modified files if you want. or you can use other argument to specify the path to  Package dir, 
see 
```shell
➜  Packages git:(master) ./depends_updater.py -h
usage: depends_updater.py [-h] [-f FILE] [-p BIOARCH_PATH] [-db DB] [--bioc_min_ver BIOC_MIN_VER] [--bioc_meta_mirror BIOC_META_MIRROR] [-o OUTPUT] [-a]

update the depends of R packages from CRAN and Bioconductor automatically

options:
  -h, --help            show this help message and exit
  -f FILE, --file FILE  The file that contains the pkgname to be archived, one pkgname per line (default: None)
  -p BIOARCH_PATH, --bioarch_path BIOARCH_PATH
                        The path of BioArchLinux repo (default: BioArchLinux)
  -db DB                The database file used to query metadata of packages (default: /tmp/dbmanager/sqlite.db)
  --bioc_min_ver BIOC_MIN_VER
                        The minimum version of Bioconductor supported, must be greater than 3.0 (default: 3.0)
  --bioc_meta_mirror BIOC_META_MIRROR
                        The server used to get all version numbers of BIOC (default: https://bioconductor.org)
  -o OUTPUT, --output OUTPUT
                        The file to save newly added depends name (default: added_depends.txt)
  -a, --auto-archive    Automatically archive pkgs that are not in CRAN or the latest BIOC release (default: False)
```

**Comment by starsareintherose** [comment]
```
./depends_updater.py -a -f list -db biometadata3.15.db  -o out.list -p ../../Packages/BioArchLinux/
INFO:root:Updating r-cvms
INFO:root:Writing new PKGBUILD for cvms
Traceback (most recent call last):
  File "/usr/share/lilac/Tools/updater/./depends_updater.py", line 385, in <module>
    update_depends_by_file(args.file, args.bioarch_path, args.db,
  File "/usr/share/lilac/Tools/updater/./depends_updater.py", line 349, in update_depends_by_file
    if auto_archive and pkginfo.is_archived():
  File "/usr/share/lilac/Tools/updater/./depends_updater.py", line 140, in is_archived
    if not self.desc:  # not in database, archived in CRAN
AttributeError: 'PkgInfo' object has no attribute 'desc'
```
could you check it on server

**Comment by sukanka** [comment]
> ```
> ./depends_updater.py -a -f list -db biometadata3.15.db  -o out.list -p ../../Packages/BioArchLinux/
> INFO:root:Updating r-cvms
> INFO:root:Writing new PKGBUILD for cvms
> Traceback (most recent call last):
>   File "/usr/share/lilac/Tools/updater/./depends_updater.py", line 385, in <module>
>     update_depends_by_file(args.file, args.bioarch_path, args.db,
>   File "/usr/share/lilac/Tools/updater/./depends_updater.py", line 349, in update_depends_by_file
>     if auto_archive and pkginfo.is_archived():
>   File "/usr/share/lilac/Tools/updater/./depends_updater.py", line 140, in is_archived
>     if not self.desc:  # not in database, archived in CRAN
> AttributeError: 'PkgInfo' object has no attribute 'desc'
> ```
> 
> could you check it on server

did you update the database first?  `biometadata3.15.db` should contain all packages from BIOC 1.8 to BIOC 3.16 and pkgs from CRAN

**Comment by starsareintherose** [comment]
Of course, I update it.

**Comment by sukanka** [comment]
> r-cvms

OK, confirmed, this function is buggy, please do not use `-a`

**Comment by sukanka** [comment]
> ```
> ./depends_updater.py -a -f list -db biometadata3.15.db  -o out.list -p ../../Packages/BioArchLinux/
> INFO:root:Updating r-cvms
> INFO:root:Writing new PKGBUILD for cvms
> Traceback (most recent call last):
>   File "/usr/share/lilac/Tools/updater/./depends_updater.py", line 385, in <module>
>     update_depends_by_file(args.file, args.bioarch_path, args.db,
>   File "/usr/share/lilac/Tools/updater/./depends_updater.py", line 349, in update_depends_by_file
>     if auto_archive and pkginfo.is_archived():
>   File "/usr/share/lilac/Tools/updater/./depends_updater.py", line 140, in is_archived
>     if not self.desc:  # not in database, archived in CRAN
> AttributeError: 'PkgInfo' object has no attribute 'desc'
> ```
> 
> could you check it on server

fixed in https://github.com/BioArchLinux/bioarchlinux-tools/commit/9726e5e0424a72b7fa2ec9d36867d5843bfd1ac5
please try again

I have tested it, it works, but DO have a look before you push it to the  master branch

**Comment by starsareintherose** [comment]
On the server is okay, but local fails
```
/depends_updater.py -a -f list -db biometadata3.15.db  -o out.list -p ../../Packages/BioArchLinux/
Traceback (most recent call last):
  File "/home/guoyi/Downloads/bioarchlinux-tools/updater/./depends_updater.py", line 438, in <module>
    update_depends_by_file(args.file, args.bioarch_path, args.db,
  File "/home/guoyi/Downloads/bioarchlinux-tools/updater/./depends_updater.py", line 363, in update_depends_by_file
    bioc_versions = get_bioc_versions(bioc_meta_mirror)
  File "/home/guoyi/Downloads/bioarchlinux-tools/updater/dbmanager.py", line 96, in get_bioc_versions
    version_page = requests.get(
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 456, in send
    conn = self.get_connection(request.url, proxies)
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 352, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 217, in proxy_manager_for
    manager = self.proxy_manager[proxy] = SOCKSProxyManager(
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 62, in SOCKSProxyManager
    raise InvalidSchema("Missing dependencies for SOCKS support.")
requests.exceptions.InvalidSchema: Missing dependencies for SOCKS support.
```

**Comment by starsareintherose** [comment]
Another thing is that how can you know if a pkg exist in which version db

**Comment by lilydjwg** [comment]
Install python-pysocks for the exception.

**Comment by starsareintherose** [comment]
still, I am not sure if the proxy influence
```
./depends_updater.py -a -f list -db biometadata3.15.db  -o out.list -p ../../Packages/BioArchLinux/
Traceback (most recent call last):
  File "/home/guoyi/Downloads/bioarchlinux-tools/updater/./depends_updater.py", line 438, in <module>
    update_depends_by_file(args.file, args.bioarch_path, args.db,
  File "/home/guoyi/Downloads/bioarchlinux-tools/updater/./depends_updater.py", line 363, in update_depends_by_file
    bioc_versions = get_bioc_versions(bioc_meta_mirror)
  File "/home/guoyi/Downloads/bioarchlinux-tools/updater/dbmanager.py", line 96, in get_bioc_versions
    version_page = requests.get(
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 456, in send
    conn = self.get_connection(request.url, proxies)
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 352, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 217, in proxy_manager_for
    manager = self.proxy_manager[proxy] = SOCKSProxyManager(
  File "/usr/lib/python3.10/site-packages/urllib3/contrib/socks.py", line 198, in __init__
    raise ValueError("Unable to determine SOCKS version from %s" % proxy_url)
ValueError: Unable to determine SOCKS version from socks://127.0.0.1:1080/
```

**Comment by starsareintherose** [comment]
@lilydjwg Could convert these scripts into pre_build function and then I can use it directly by adding function to lilac.yaml?

**Comment by lilydjwg** [comment]
Use `socks5://`?

Yes if I can figure out how to use them.

**Comment by sukanka** [comment]
> Another thing is that how can you know if a pkg exist in which version db

search it in cran first, if not found, then search in BIOC 3.16,3.15 and so on. If not found in the database, it's archived in CRAN

A detailed one

get pkg from database

cases:
* not found => archived in CRAN
* found, match BIOC VER
    * 3.16 (latest)  => Not archived, pkg is in BIOC
    * None => pkg in CRAN and not archived
    * Other (e.g. 3.15,3.14,...) => archived in BIOC

**Comment by starsareintherose** [comment]
> Use `socks5://`?
> 
> Yes if I can figure out how to use them.

I am not sure how to do so

**Comment by starsareintherose** [comment]
> Use `socks5://`?
> 
> Yes if I can figure out how to use them.

@sukanka could you help @lilydjwg

**Comment by sukanka** [comment]
> > Use `socks5://`?
> > Yes if I can figure out how to use them.
> 
> @sukanka could you help @lilydjwg

Maybe, I don't get what the problem is.
I didn't take proxy into consideration.
BTW, I recommend you to use transparent proxy, so you don't need such socks5

**Comment by lilydjwg** [comment]
I don't know what these scripts are doing (how are they used?). If you want to generate PKGBUILDs, you can see what `lilac2/*2pkgbuild.py` are doing.

**Comment by sukanka** [comment]
> I don't know what these scripts are doing (how are they used?). If you want to generate PKGBUILDs, you can see what `lilac2/*2pkgbuild.py` are doing.

There are several difficulties when maintaining R packages in CRAN and BioConductor(BIOC)
1. `depends` of a package may and often change when there is an update, causing it failed to be built.
2. a package may become archived (disappear in CRAN, or removed from a newer version of BIOC), and, perhaps some days latter, come back to CRAN again (unarchive)!

These scripts are designed to deal with those two things.
1. `dbmanager` is used to keep an up-to-date  metadata of packages in CRAN and BIOC, which we used to infer whether it is archived (or it is already archived, but becomes unarchived).
2. `depends_updater` is used to do all the dirty things. It reads database generated by `dbmanager`, then 
  a. refresh `depends` and `optdepends` in PKGBUILD, update `lilac.yaml` accordingly
  b. check whether it becomes archived (or unarchived), if so, update the source url  in PKGBUILD and url used to check for updates in `lilac.yaml` 

The only case we need to generate PKGBUILDs is new dependencies are needed, which is not in our (and official) repo, so we need to use [PKGBUILD Generator for R](https://github.com/BioArchLinux/pkgbuild-generator-for-r/tree/master/PKGBUILDGenerator)  to make  PKGBUILDs. It works just fine.

**Comment by lilydjwg** [comment]
So complex! This can't be moved into `lilac.yaml`. It has to be a step prior to a lilac run.
